### PR TITLE
I18N support

### PR DESCRIPTION
**Pull request by poum**
Adding I18N yadda fonctionnality handling using a new "language" config option
(English is used by default)
BUG: moonraker reporter does'nt work when language is'nt English

### CODE REVIEW

**Comment by poum** [comment]
Works with mocha reporters but fail with moonraker reporter but I can't figure why ...

**Comment by dannyjhall** [comment]
Hi,

Thanks. The problem with this was the handlebars template was in English. I've updated it with a helper to support different languages and also added a [translations](https://github.com/LateRoomsGroup/moonraker/blob/i18n/lib/reporter/i18n/translations.json) file so the report can be translated into any languages that may be required - this is only a quick example though (using Google translate :/) so it may not be accurate.

You should be able to just set the `language` in the config and the correct Yadda & report language will be used, defaulting to English for both.

It's all in a new [branch](https://github.com/LateRoomsGroup/moonraker/tree/i18n) ready to be merged in for the next release.

Thanks again!

**Comment by poum** [comment]
Ok, great ! I've seen that template needed to be translated to but I didn't expect that could throw an error ... I've slightly improved the french part in language file. What about untranslated ones ? Will this throw an error or just revert to english as default ? If so, I suggest to update the Readme files ...

**Comment by poum** [comment]
By the way, I'm not really satisfied with my duplicates switch/case statements. I'm sure, it should be a more elegant and more maintenable way to do it ...

**Comment by poum** [comment]
WARNING: adding a I18N example, I noticed that, line 47, loadStepDefs(language) should be replaced by loadStepDefs(myLanguage) in order the test works ....

**Comment by dannyjhall** [comment]
Hi,

If a translation for the report isn't available (or for a specific word) it will revert to English. I'll update the readme with the language info before publishing the next update. Please see my comment on [PR#4](https://github.com/LateRoomsGroup/moonraker/pull/5) about the parser/steps language..

Thanks for your help!

**Pull request closed without merging**
