### PR TITLE
BrowserStack service support

### PR DESCRIPTION
**Pull request by vectart**
Also includes small refactoring that allows to link the NPM module.

### CODE REVIEW

**Comment by dannyjhall** [comment]
Hi,

Thanks for this... but Moonraker already supports Browserstack / Saucelabs etc via the normal remote webdriver connection, you just need to include your user / key in the browser capabilities (along with the browser configurations they support) in the config:

Browserstack:
```json
"seleniumServer": "http://hub.browserstack.com/wd/hub",

  "browser": {
    "browserstack.user": "USERNAME",
    "browserstack.key": "KEY",
    "browserName": "Safari",
    "browser_version": "8.0",
    "os": "OS X",
    "os_version": "Yosemite",
    "resolution": "1920x1080"
  }
```
Saucelabs:
```json
"seleniumServer": "http://ondemand.saucelabs.com:80/wd/hub",

  "browser": {
    "username": "USERNAME",
    "accessKey": "KEY",
    "browserName": "safari",
    "version": "8.0",
    "platform": "OS X 10.10"
  }
```
I'm not sure what benefits the dependency [browserstack-webdriver](https://github.com/browserstack/selenium-webdriver-nodejs) brings, but its not had any activity since May 2014 and seems to be using an older version of selenium-webdriver (2.40.0)..

**Comment by vectart** [comment]
@dannyjhall I haven't realise that, that's awesome!
Could be this useful documentation added to README.md?

**Comment by dannyjhall** [comment]
@vectart Absolutely! I'll make sure its updated with these examples.

**Comment by vectart** [comment]
@dannyjhall Wonderful, thank you very much!

**Pull request closed without merging**
